#!/usr/bin/env ruby

require 'date'
lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'strftime'

# If the argument appears like "%y" just output the description
# otherwise, find the format for the given date

given_date = ARGV[0]

if given_date
  STDOUT.puts Strftime::InstructionSet.new(given_date).to_s
else
  STDOUT.puts Strftime::Directive.all.sort
end
